/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPack;

import DatabasePack.GetPack.GetDataFromPersonDB;
import InsertDBPack.InsertPersonDB;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author faysal
 */
public class InsertPersonsFrame extends javax.swing.JFrame {

    GetDataFromPersonDB getPerson=new GetDataFromPersonDB();
    /**
     * Creates new form InsertPersonsFrame
     */
    public InsertPersonsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idtf = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        emailtf = new javax.swing.JTextField();
        libcardtf = new javax.swing.JTextField();
        memtypetf = new javax.swing.JTextField();
        addtf = new javax.swing.JTextField();
        con1tf = new javax.swing.JTextField();
        con2tf = new javax.swing.JTextField();
        issuebooktf = new javax.swing.JTextField();
        personOkButton = new javax.swing.JButton();
        personCancelButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insert Person Form");
        setIconImage(new ImageIcon(getClass().getResource("/icon/icon1.jpg")).getImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please Fill Up The Following Info :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Person's ID :>");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name :>");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("E-Mail :>");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Library Card No :>");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Member Type :>");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Address :>");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Contact No 1 :>");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Contact No 2 :>");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Issue Books Number :>");
        jLabel10.setToolTipText("Keep It > 0");

        idtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nametf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });

        emailtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        libcardtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        libcardtf.setText("must be number and not begin with 0");

        memtypetf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        con1tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        con2tf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        issuebooktf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        issuebooktf.setToolTipText("MUST BE NUMBER  AND NOT BLANK");

        personOkButton.setText("OK");
        personOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personOkButtonActionPerformed(evt);
            }
        });

        personCancelButton.setText("CANCEL");
        personCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(personOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(personCancelButton))
                    .addComponent(idtf)
                    .addComponent(nametf)
                    .addComponent(emailtf)
                    .addComponent(libcardtf)
                    .addComponent(memtypetf)
                    .addComponent(addtf)
                    .addComponent(con1tf)
                    .addComponent(con2tf)
                    .addComponent(issuebooktf))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(libcardtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(memtypetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(con1tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(con2tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuebooktf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personOkButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(personCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personOkButtonActionPerformed
      
        String id, name, email, libcard, memType, address, cont1, cont2, issue;
        
        int issuint = 500;
        id= idtf.getText().toString();
        
        name= nametf.getText().toString();
        
        email= emailtf.getText().toString();
        
        libcard= libcardtf.getText().toString();
        
        memType= memtypetf.getText().toString();
        
        address= addtf.getText().toString();
        
        cont1= con1tf.getText().toString();
        
        cont2= con2tf.getText().toString();
        
        issue= issuebooktf.getText().toString();
        
        
        if(idtf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter ID!");
        }
        else if(nametf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter name!");
        }
        else if(emailtf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter email!");
        }
        else if(libcardtf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter library card!");
        }
        else if(memtypetf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter your member type!");
        }
        else if(addtf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter address!");
        }
        else if(con1tf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter contact1 (at least One contact should be inserted)!");
        }
        else if(issuebooktf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter issue book number..");
        }
        
        if(!issuebooktf.equals(""))
        {
        try{
        issuint= Integer.parseInt(issue);
        System.out.println(issuint);
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(this, "IssueBooks must be number ..... Wrong InforMation !!!","Wrong Info",JOptionPane.ERROR_MESSAGE);
             System.exit(0);
        }
        
        
        }
        if(!issuebooktf.equals("") && issuint>0)
            {
             JOptionPane.showMessageDialog(this, "Issue books  number is too much.. ?? !!!");
             issuebooktf.setText("");
            }
        
        if(getPerson.getPersonNameExistFromDB(name))
        {
        JOptionPane.showMessageDialog(this, "Person name is already exist....");
        nametf.setText("");
        }
        else if(getPerson.getPersongIDExistFromDB(id))
        {
        JOptionPane.showMessageDialog(this, "Person ID is already exist....");
        idtf.setText("");
        }
        else if(getPerson.getLibCardExistFromDB(libcard))
        {
        JOptionPane.showMessageDialog(this, "Person Library Card is already exist....");
        libcardtf.setText("");
        }        
       
        if((!idtf.getText().equals(""))&&(!nametf.getText().equals(""))&&(!emailtf.getText().equals(""))&&(!libcardtf.getText().equals(""))&&(!memtypetf.getText().equals(""))&&(!addtf.getText().equals(""))&&(!con1tf.getText().equals(""))
                &&(!issuebooktf.getText().equals("")&& !(issuint>1))&&(!getPerson.getPersonNameExistFromDB(name))&&(!getPerson.getPersongIDExistFromDB(id))&&(!getPerson.getLibCardExistFromDB(libcard)))
        {
        
            InsertPersonDB insertperson=new InsertPersonDB();
            
            insertperson.InsertToDB(id, libcard, memType, name, email, address, cont1, cont2, issue);
            JOptionPane.showMessageDialog(this, "Person Info Successfully Added....");
            JOptionPane.showMessageDialog(this, "..Please Enter Refresh Button To Update Books Info..");
            
            idtf.setText("");
        nametf.setText("");
        emailtf.setText("");
        libcardtf.setText("");
        memtypetf.setText("");
        addtf.setText("");
        con1tf.setText("");
        con2tf.setText("");
        issuebooktf.setText("");
            
            this.dispose();
    
        }
        else
        {
        JOptionPane.showMessageDialog(this, "Please enter info again...");
        /*
        idtf.setText("");
        nametf.setText("");
        emailtf.setText("");
        libcardtf.setText("");
        memtypetf.setText("");
        addtf.setText("");
        con1tf.setText("");
        con2tf.setText("");
        issuebooktf.setText("");
        
        */
        }
        
         
    }//GEN-LAST:event_personOkButtonActionPerformed

    private void personCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personCancelButtonActionPerformed
         idtf.setText("");
        nametf.setText("");
        emailtf.setText("");
        libcardtf.setText("");
        memtypetf.setText("");
        addtf.setText("");
        con1tf.setText("");
        con2tf.setText("");
        issuebooktf.setText("");
        
        this.dispose();
    }//GEN-LAST:event_personCancelButtonActionPerformed

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertPersonsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertPersonsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertPersonsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertPersonsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertPersonsFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addtf;
    private javax.swing.JTextField con1tf;
    private javax.swing.JTextField con2tf;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField idtf;
    private javax.swing.JTextField issuebooktf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField libcardtf;
    private javax.swing.JTextField memtypetf;
    private javax.swing.JTextField nametf;
    private javax.swing.JButton personCancelButton;
    private javax.swing.JButton personOkButton;
    // End of variables declaration//GEN-END:variables
}
