/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPack;

import DatabasePack.GetPack.GetDataFromBooksDB;
import InsertDBPack.InsertBooksDB;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author faysal
 */
public class InsertBooksFrame extends javax.swing.JFrame {

   GetDataFromBooksDB getDataBooksDBobj=new GetDataFromBooksDB();
    /**
     * Creates new form InsertBooksFrame
     */
    InsertBooksDB insertBooks=new InsertBooksDB();
    GetDataFromBooksDB getData=new GetDataFromBooksDB();
    public InsertBooksFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bidtf = new javax.swing.JTextField();
        titletf = new javax.swing.JTextField();
        grouptf = new javax.swing.JTextField();
        serialtf = new javax.swing.JTextField();
        isbntf = new javax.swing.JTextField();
        authortf = new javax.swing.JTextField();
        availabilitytf = new javax.swing.JTextField();
        fillupokbutton = new javax.swing.JButton();
        fillupcancelbutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Books Fill Up Form");
        setIconImage(new ImageIcon(getClass().getResource("/icon/icon1.jpg")).getImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fill Up The Following Info :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Books Id :>");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Books  Title :>");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Books Group :>");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Books Serial :>");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Books ISBN No :>");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Books Author :>");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Books Availability :>");

        bidtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bidtf.setText("must be number and not begin with 0");
        bidtf.setToolTipText("must be number and not begin with 0");

        titletf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        grouptf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        serialtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        isbntf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        authortf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        availabilitytf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fillupokbutton.setText("OK");
        fillupokbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillupokbuttonActionPerformed(evt);
            }
        });

        fillupcancelbutton.setText("CANCEL");
        fillupcancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillupcancelbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fillupokbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(fillupcancelbutton))
                    .addComponent(bidtf)
                    .addComponent(titletf)
                    .addComponent(grouptf)
                    .addComponent(serialtf)
                    .addComponent(isbntf)
                    .addComponent(authortf)
                    .addComponent(availabilitytf))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titletf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grouptf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authortf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availabilitytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fillupokbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(fillupcancelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillupokbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillupokbuttonActionPerformed
        
        
        String id, title, group, serial, isbn, author;
        String availability;
        int aval=500;
        id= bidtf.getText().toString();
        title= titletf.getText().toString();
        group= grouptf.getText().toString();
        serial= serialtf.getText().toString();
        isbn= isbntf.getText().toString();
        author= authortf.getText().toString();
        availability= availabilitytf.getText().toString();
        
       
         
         
       
        if(bidtf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter books id!");
        }
        else if(titletf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter books title!");
        }
        else if(grouptf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter books group!");
        }
        else if(serialtf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter books serial!");
        }
        else if(isbntf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter books isbn number!");
        }
        else if(authortf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter books author name!");
        }
        else if(availabilitytf.getText().equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter book is available or not (this must be number)!");
        }
        
         
        
        if(!availability.equals(""))
        {
            try{
            aval= Integer.parseInt(availability);
            }
            catch(NumberFormatException e)
            { 
                JOptionPane.showMessageDialog(this, "Availability must be number ..... Wrong InforMation !!!","Wrong Info",JOptionPane.ERROR_MESSAGE);
             System.exit(0);
            }
            
            if(aval>100)
            {
             JOptionPane.showMessageDialog(this, "Books available number is too much.. ?? !!!");
             availabilitytf.setText("");
            }
            else
                 {       
                     
                     
             System.out.println("OK");
             
            // 
            
                 if(getData.getBookIdExistFromDB(id))
                 {
                 JOptionPane.showMessageDialog(this, "Book id is already available");
                 }
                 else if(getData.getBookSerialExistFromDB(serial))
                 {
                 JOptionPane.showMessageDialog(this, "Book serial is already available");
                 }
                 else if(getData.getBookIsbnExistFromDB(isbn))
                 {
                 JOptionPane.showMessageDialog(this, "Book ISBN is already available");
                 }
                 else
                 {
                 /*
                 insertBooks.InsertToDB(id, title, group, serial, isbn, author, aval);
                 
                 JOptionPane.showMessageDialog(this, "Books Info Successfully Added...");
                 
                 JOptionPane.showMessageDialog(this, "..Please Enter Refresh Button To Update Books Info..");
                 
                 bidtf.setText("");
                 titletf.setText("");
                 grouptf.setText("");
                 serialtf.setText("");
                 isbntf.setText("");
                 authortf.setText("");
                 availabilitytf.setText("");
                 */
                // serviceFrommainObj.setList();
                 
             //    InsertBooksFrame.this.dispose();
                 
                 }
                 }
            
           
        }
        
        if((!bidtf.getText().equals(""))&&(!titletf.getText().equals(""))&&(!grouptf.getText().equals(""))&&(!serialtf.getText().equals(""))&&(!isbntf.getText().equals(""))&&(!authortf.getText().equals(""))
                &&(!availabilitytf.getText().equals(""))&&(!getData.getBookIdExistFromDB(id))&&(!getData.getBookSerialExistFromDB(serial))&&(!getData.getBookIsbnExistFromDB(isbn)))
        {
        insertBooks.InsertToDB(id, title, group, serial, isbn, author, aval);
                 
                 JOptionPane.showMessageDialog(this, "Books Info Successfully Added...");
                 
                 JOptionPane.showMessageDialog(this, "..Please Enter Refresh Button To Update Books Info..");
                 
                 
                 bidtf.setText("");
                 titletf.setText("");
                 grouptf.setText("");
                 serialtf.setText("");
                 isbntf.setText("");
                 authortf.setText("");
                 availabilitytf.setText("");
                 
                 InsertBooksFrame.this.dispose();
        
        }
        else{
        JOptionPane.showMessageDialog(this, "Please enter info again...");
        }
        
        
        
        
    }//GEN-LAST:event_fillupokbuttonActionPerformed

    private void fillupcancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillupcancelbuttonActionPerformed
       bidtf.setText("");
                 titletf.setText("");
                 grouptf.setText("");
                 serialtf.setText("");
                 isbntf.setText("");
                 authortf.setText("");
                 availabilitytf.setText("");
                 
                 InsertBooksFrame.this.dispose();
    }//GEN-LAST:event_fillupcancelbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
   
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertBooksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertBooksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertBooksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertBooksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertBooksFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authortf;
    private javax.swing.JTextField availabilitytf;
    private javax.swing.JTextField bidtf;
    private javax.swing.JButton fillupcancelbutton;
    private javax.swing.JButton fillupokbutton;
    private javax.swing.JTextField grouptf;
    private javax.swing.JTextField isbntf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField serialtf;
    private javax.swing.JTextField titletf;
    // End of variables declaration//GEN-END:variables
}
