/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPack;

import DatabasePack.GetPack.GetDataFromBooksDB;
import DatabasePack.GetPack.GetDataFromPersonDB;
import DatabasePack.GetPack.GetDataFromServiceDB;
import DatabasePack.UpdatePack.UpdateBooksNumber;
import DatabasePack.UpdatePack.UpdateIssueBooksDataPersonDB;
import DatabasePack.deletePack.DeleteDataFineDB;
import DatabasePack.deletePack.DeleteDataServiceDB;
import InsertDBPack.InsertFineDB;
import Main.DateDiff;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author faysal
 */
public class ReturnFrame extends javax.swing.JFrame {

    GetDataFromServiceDB getservice =new GetDataFromServiceDB();
    /**
     * Creates new form ReturnFrame
     */
    
      
    private static final Object[][] rowData = {};
private static final Object[] columnNames = {"Librarian Official ID: ", "Books ID: ","Issue Date: ", "Return Date: "};
    

DefaultTableModel listTableModel;

int FineRate=10;
    
    public ReturnFrame() {
        initComponents();
        
        dueDatetf.setEditable(false);
        finetf.setEditable(false);
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ReturnOk = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        libcardTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        dueDatetf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        finetf = new javax.swing.JTextField();
        payButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Return & Pay form :");
        setIconImage(new ImageIcon(getClass().getResource("/icon/icon1.jpg")).getImage());
        setResizable(false);

        ReturnOk.setText("OK");
        ReturnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnOkActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        libcardTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter Library Card No :");

        jTable1.setModel(listTableModel = new DefaultTableModel(rowData, columnNames));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Due Date :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fine Amount : (TAKA)");
        jLabel2.setToolTipText("10 TK per Day");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libcardTf, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dueDatetf)
                            .addComponent(finetf))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(libcardTf, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dueDatetf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finetf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        payButton.setText("PAY / RETURN");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(payButton)
                .addGap(138, 138, 138)
                .addComponent(ReturnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(payButton, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(ReturnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnOkActionPerformed
        String libcard;
        
        libcard= libcardTf.getText().toString();
       
     
        
        
        if(libcard.equals(""))
        {
        JOptionPane.showMessageDialog(this, "Please enter Library Card !");
        }
        
        if(!libcard.equals(""))
        {
        if(getservice.getLibCardExistFromDB(libcard))
        {
            
            GetDataFromPersonDB getPerson=new GetDataFromPersonDB();
         String gk[][]=getservice.getAllServiceInfoFromLibCardFromDB(libcard);
                          
       for(int i=0;i<getPerson.getIssueBooksNumFromDB(libcard);++i)
      {
          for(int j=0;j<1;++j)
          {
                   
          listTableModel.addRow(new Object[]{gk[i][j],gk[i][j+1],gk[i][j+2],gk[i][j+3]});
               
          }  
          
      }        
        
        
        
        }
        
        }
        
        
        
        
        
        //calculate...date..........diffrence.............
        
       // String issueDate= getservice.getIssueDateFromDB(libcard);
        String returnDate= getservice.getReturnDateFromDB(libcard);
        
         DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
       //get current date time with Date()
       Date date = new Date();
       
       String today= dateFormat.format(date);
     //  System.out.println(today);
        
        
        
        if(returnDate!=null){
        DateDiff dd=new DateDiff();
        
        long dueDate= dd.getDateDifference( returnDate, today);
                 
        
        dueDatetf.setText(String.valueOf(dueDate));
        
        String setFine= String.valueOf(FineRate* dueDate);
        
        finetf.setText(setFine);
        
        if(dueDate>0)
        {
        InsertFineDB insertFine=new InsertFineDB();
        
        insertFine.InsertToDB(libcard, String.valueOf(dueDate), Integer.parseInt(setFine));
        
        JOptionPane.showMessageDialog(this, "You've been FINED...");
        }
        else
        {
        JOptionPane.showMessageDialog(this, "You're not FINED...");
        dueDatetf.setText("");
        finetf.setText("NO FINE");
        }
        
        }
        else
        {
        JOptionPane.showMessageDialog(this, "No Entry.. Yet...");
        }
        
        
        
        
        
    }//GEN-LAST:event_ReturnOkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        libcardTf.setText("");
        dueDatetf.setText("");
        finetf.setText("");
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
       GetDataFromPersonDB getPerson=new GetDataFromPersonDB();
       String libcard=libcardTf.getText().toString();
       int issuedbooks = 0;
       if(libcard!=null)
       {
        issuedbooks= getPerson.getIssueBooksNumFromDB(libcard);
       
       
       if(issuedbooks!=0){
           String subtractIssuedBooks=String.valueOf(issuedbooks-1);
           System.out.println("Sub issued Books> "+subtractIssuedBooks+" Issue> "+issuedbooks);
        UpdateIssueBooksDataPersonDB update=new UpdateIssueBooksDataPersonDB(subtractIssuedBooks, libcard);
        
        
                
        GetDataFromBooksDB getbookin=new GetDataFromBooksDB();
        GetDataFromServiceDB getservice=new GetDataFromServiceDB();
        
        System.out.println("LIB,,,,>"+libcard);
        String booksId= getservice.getBooksIDFromDB(libcard);
        if(booksId!=null){
        int booksnum= getbookin.getAvailableBooksFromDB(booksId);
         System.out.println("Bok1> "+booksnum);
        String booksStnum= String.valueOf(booksnum+1);
       System.out.println("Bok> "+booksStnum);
       UpdateBooksNumber updatebooksnum=new UpdateBooksNumber(booksStnum, booksId);
        }
        else
        {
        JOptionPane.showMessageDialog(this, "No books taken...for library card : "+libcard);
        }
        
        
        DeleteDataServiceDB deleteService=new DeleteDataServiceDB();
        
        deleteService.deleteItem(libcard);
        
        DeleteDataFineDB deleteFine= new DeleteDataFineDB();
        
        deleteFine.deleteItem(libcard);
        
                JOptionPane.showMessageDialog(this, "Successfully Updated.. ");
        this.dispose();
                }
       
       }
       
       else{
       JOptionPane.showMessageDialog(this, "Problem with issued books number...!!");
       
       }
       
    }//GEN-LAST:event_payButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ReturnFrame obj=new ReturnFrame();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnOk;
    private javax.swing.JTextField dueDatetf;
    private javax.swing.JTextField finetf;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField libcardTf;
    private javax.swing.JButton payButton;
    // End of variables declaration//GEN-END:variables
}
