/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPack;

import DatabasePack.GetPack.*;
import DatabasePack.UpdatePack.UpdateBooksNumber;
import DatabasePack.UpdatePack.UpdateIssueBooksDataPersonDB;
import DatabasePack.deletePack.DeleteDataBookDB;
import InsertDBPack.InsertServiceDB;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author faysal
 */
public class ServiceFormMain extends javax.swing.JFrame {

      InsertBooksFrame insertBookobj =new InsertBooksFrame();
        InsertPersonsFrame insertPersonobj=new InsertPersonsFrame();
        
        
        ServiceForm serviceobj=new ServiceForm();
        FineForm fineobj=new FineForm();
        
        
        GetDataFromBooksDB getDataBooksDBobj=new GetDataFromBooksDB();
        GetDataFromPersonDB getDataPerson=new GetDataFromPersonDB();
        GetDataFromLibrarianDB getDataLib=new GetDataFromLibrarianDB();
        
        
        
        
        String permittableIssueBookNumber= String.valueOf(1);
        
        
    /**
     * Creates new form ServiceFormMain
     */
    public ServiceFormMain() {
        
      
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bookList = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        personList = new javax.swing.JList();
        jPanel7 = new javax.swing.JPanel();
        insertBooksButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        insertPersonbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        servicebutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fineButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        librarycardtf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        booksidtf = new javax.swing.JTextField();
        issuedatetf = new javax.swing.JTextField();
        returndatetf = new javax.swing.JTextField();
        librarianOidtf = new javax.swing.JTextField();
        serveOkButton = new javax.swing.JButton();
        serveCancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        deleteBooksDBbutton = new javax.swing.JButton();
        deletePersonDBbutton = new javax.swing.JButton();
        deleteServiceDBbutton = new javax.swing.JButton();
        deleteFineDBButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksInfoList = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        personInfoList = new javax.swing.JList();
        refreshBooksInfobutton = new javax.swing.JButton();
        refreshMembersInfobutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Service");
        setIconImage(new ImageIcon(getClass().getResource("/icon/icon1.jpg")).getImage());

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTabbedPane1PropertyChange(evt);
            }
        });

        bookList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        bookList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bookListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(bookList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Books List", jPanel3);

        personList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        personList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                personListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(personList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Permittable Persons List", jPanel4);

        insertBooksButton.setBackground(new java.awt.Color(255, 255, 255));
        insertBooksButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPack/Resource/b34.jpg"))); // NOI18N
        insertBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBooksButtonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Insert New Book :");

        insertPersonbutton.setBackground(new java.awt.Color(255, 255, 255));
        insertPersonbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPack/Resource/person2.jpg"))); // NOI18N
        insertPersonbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPersonbuttonActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Insert New Person :");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Service :");

        servicebutton.setBackground(new java.awt.Color(255, 255, 255));
        servicebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPack/Resource/service.jpg"))); // NOI18N
        servicebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicebuttonActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fine :");

        fineButton.setBackground(new java.awt.Color(255, 255, 255));
        fineButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPack/Resource/fine.jpg"))); // NOI18N
        fineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fineButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Return :");

        returnButton.setBackground(new java.awt.Color(255, 255, 255));
        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPack/Resource/return.jpg"))); // NOI18N
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertPersonbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(servicebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertPersonbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(servicebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Options ", jPanel7);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Please Enter Your Library Card No :>");

        librarycardtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Please Enter Your Books ID :>");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Please Enter Issue Date :> (14/02/2014)");
        jLabel9.setToolTipText("14/02/2014");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Your Return Date :> (15 auto)");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Librarian Official ID :>");

        booksidtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        issuedatetf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        issuedatetf.setText("day/month/year");
        issuedatetf.setToolTipText("Press Enter To Get Return Date Automatically...");
        issuedatetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedatetfActionPerformed(evt);
            }
        });

        returndatetf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        returndatetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returndatetfActionPerformed(evt);
            }
        });

        librarianOidtf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        serveOkButton.setBackground(new java.awt.Color(255, 255, 255));
        serveOkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPack/Resource/ok.jpg"))); // NOI18N
        serveOkButton.setToolTipText("OK ");
        serveOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveOkButtonActionPerformed(evt);
            }
        });

        serveCancelButton.setBackground(new java.awt.Color(255, 255, 255));
        serveCancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPack/Resource/cance01l.jpg"))); // NOI18N
        serveCancelButton.setToolTipText("CANCEL");
        serveCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serveCancelButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPack/Resource/b2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(serveOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(serveCancelButton))
                    .addComponent(librarycardtf)
                    .addComponent(booksidtf)
                    .addComponent(issuedatetf)
                    .addComponent(returndatetf)
                    .addComponent(librarianOidtf))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librarycardtf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booksidtf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuedatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returndatetf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librarianOidtf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(serveCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(serveOkButton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Serve Books", jPanel8);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Reset All Services :>");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Reset Books Database :");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Reset Persons Database :");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Reset Service Database :");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Reset Fine Database :");

        deleteBooksDBbutton.setText("Delete Info");
        deleteBooksDBbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBooksDBbuttonActionPerformed(evt);
            }
        });

        deletePersonDBbutton.setText("Delete Info");

        deleteServiceDBbutton.setText("Delete Info");

        deleteFineDBButton.setText("Delete Info");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBooksDBbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(deletePersonDBbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteServiceDBbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteFineDBButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBooksDBbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletePersonDBbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteServiceDBbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteFineDBButton))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reset ", jPanel9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        booksInfoList.setBorder(javax.swing.BorderFactory.createTitledBorder("< Books Information >"));
        booksInfoList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(booksInfoList);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        personInfoList.setBorder(javax.swing.BorderFactory.createTitledBorder("< Member's Info >"));
        personInfoList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(personInfoList);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        refreshBooksInfobutton.setText("Refresh");
        refreshBooksInfobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBooksInfobuttonActionPerformed(evt);
            }
        });

        refreshMembersInfobutton.setText("Refresh");
        refreshMembersInfobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshMembersInfobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(refreshBooksInfobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(72, 72, 72)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(refreshMembersInfobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(93, 93, 93))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshBooksInfobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshMembersInfobutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBooksButtonActionPerformed
        insertBookobj.setVisible(true);
        insertBookobj.setLocationRelativeTo(null);
    }//GEN-LAST:event_insertBooksButtonActionPerformed

    private void insertPersonbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPersonbuttonActionPerformed
       insertPersonobj.setVisible(true);
       insertPersonobj.setLocationRelativeTo(null);
    }//GEN-LAST:event_insertPersonbuttonActionPerformed

    private void servicebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicebuttonActionPerformed
     serviceobj.setVisible(true);
     serviceobj.setLocationRelativeTo(null);
    }//GEN-LAST:event_servicebuttonActionPerformed

    private void fineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fineButtonActionPerformed
       fineobj.setVisible(true);
       fineobj.setLocationRelativeTo(null);
    }//GEN-LAST:event_fineButtonActionPerformed

    private void bookListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bookListValueChanged
      
        String getSelectedValue= (String) bookList.getSelectedValue();
        if(!evt.getValueIsAdjusting() && getSelectedValue!=null){
       String booksInfo[]= getDataBooksDBobj.getAllInfoFromDB(getSelectedValue);
       int infoSize= getDataBooksDBobj.LastID();
        if(infoSize!=0){
                    DefaultListModel dlm=new DefaultListModel();
                
                     for(String wan: booksInfo)
                        {
                            if(wan!=null) {
                                    dlm.addElement(wan);
                                  //  System.out.println(">>>>"+dlm.toString());
                                }
                        }
                
                    
                     
                         booksInfoList.setModel(dlm);
                         //System.out.println(">>>>>>"+jList1);
                }
                else
                {
              //  JOptionPane.showMessageDialog(rootPane,"Sorry.. there is no item..!", "Error !", JOptionPane.ERROR_MESSAGE);
                DefaultListModel dlm=new DefaultListModel();
                dlm.addElement("No Books Info In Database !");
                booksInfoList.setModel(dlm);
                }
        }
    }//GEN-LAST:event_bookListValueChanged

    private void refreshBooksInfobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBooksInfobuttonActionPerformed
     
        
        DefaultListModel dlm=new DefaultListModel();
        
        dlm.addElement("");
        bookList.setModel(dlm);
                String getBooksName[]= getDataBooksDBobj.getBNFromDB();
                int lengthofid=getDataBooksDBobj.LastID();
                
              //  System.out.println(">>"+lengthofid);
                if(lengthofid!=0){
                    
                
                     for(String wan: getBooksName)
                        {
                          //  System.out.println(wan);
                            if(wan!=null) {
                              //  System.out.println(".."+wan);
                                    dlm.addElement(wan);
                               //    System.out.println(">>>>"+dlm.toString());
                                }
                        }
                
                    
                     try{
                         bookList.setModel(dlm);
                     }
                     catch(Exception e )
                     {
                     System.out.println("Ex... "+e);
                     }
                     
                     //System.out.println(">>>>>>"+jList1);
                }
                else
                {
              //  JOptionPane.showMessageDialog(rootPane,"Sorry.. there is no item..!", "Error !", JOptionPane.ERROR_MESSAGE);
            //    DefaultListModel dlm=new DefaultListModel();
                dlm.addElement("No Books In DB");
                bookList.setModel(dlm);
                }
    
               
    }//GEN-LAST:event_refreshBooksInfobuttonActionPerformed

    private void jTabbedPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1PropertyChange
        
    }//GEN-LAST:event_jTabbedPane1PropertyChange

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        
      
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void refreshMembersInfobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshMembersInfobuttonActionPerformed
         
        DefaultListModel dlm=new DefaultListModel();
        
        dlm.addElement("");
        personList.setModel(dlm);
                String getpersonName[]= getDataPerson.getPNFromDB();
                int lengthofid=getDataPerson.LastID();
                
              //  System.out.println(">>"+lengthofid);
                if(lengthofid!=0){
                    
                
                     for(String wan: getpersonName)
                        {
                          //  System.out.println(wan);
                            if(wan!=null) {
                              //  System.out.println(".."+wan);
                                    dlm.addElement(wan);
                               //    System.out.println(">>>>"+dlm.toString());
                                }
                        }
                
                    
                     try{
                         personList.setModel(dlm);
                     }
                     catch(Exception e )
                     {
                     System.out.println("Ex... "+e);
                     }
                     
                     //System.out.println(">>>>>>"+jList1);
                }
                else
                {
              //  JOptionPane.showMessageDialog(rootPane,"Sorry.. there is no item..!", "Error !", JOptionPane.ERROR_MESSAGE);
            //    DefaultListModel dlm=new DefaultListModel();
                dlm.addElement("No Member In DB");
                personList.setModel(dlm);
                }
    
    }//GEN-LAST:event_refreshMembersInfobuttonActionPerformed

    private void personListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_personListValueChanged
       
        String getSelectedValue= (String) personList.getSelectedValue();
       // System.out.println(getSelectedValue);
         // if(!evt.getValueIsAdjusting()) {
                 //       System.out.println("URL IS : "+getSelectedValue);
          //          }
       
        if(!evt.getValueIsAdjusting()&& getSelectedValue!=null){
     // System.out.println( getDataPerson.getAllPersonInfoFromDB(getSelectedValue));
            String personInfo[]= getDataPerson.getAllPersonInfoFromDB(getSelectedValue);
       int infoSize= getDataPerson.LastID();
       
    //   System.out.println(">>"+infoSize+" "+personInfo);
        if(infoSize!=0){
                    DefaultListModel dlm=new DefaultListModel();
                
                     for(String wan: personInfo)
                        {
                            if(wan!=null) {
                                    dlm.addElement(wan);
                                  //  System.out.println(">>>>"+dlm.toString());
                                }
                        }
                
                    
                     
                         personInfoList.setModel(dlm);
                        //System.out.println(">>>>>>"+jList1);
                }
                else
                {
              //  JOptionPane.showMessageDialog(rootPane,"Sorry.. there is no item..!", "Error !", JOptionPane.ERROR_MESSAGE);
                DefaultListModel dlm=new DefaultListModel();
                dlm.addElement("No Member Info In Database !");
               personInfoList.setModel(dlm);
                }
        }
    }//GEN-LAST:event_personListValueChanged

    private void serveOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveOkButtonActionPerformed
        String libcardno,booksId,issueDate, returnDate, libOfficialID;
        
        libcardno= librarycardtf.getText().toString();
        booksId= booksidtf.getText().toString();
        issueDate= issuedatetf.getText().toString();
        returnDate=returndatetf.getText().toString();
        libOfficialID=librarianOidtf.getText().toString();
        
        
        int getIssuedBooksNumber= getDataPerson.getIssueBooksNumFromDB(libcardno);
        
        //System.out.println(">> issssss"+getIssuedBooksNumber);
        
        
        
        if(librarycardtf.getText().equals(""))
        {
         JOptionPane.showMessageDialog(this, "Please enter library card no !");
        }
        else if(booksidtf.getText().equals(""))
        {
         JOptionPane.showMessageDialog(this, "Please enter books id !");
        }
        else if(issuedatetf.getText().equals(""))
        {
         JOptionPane.showMessageDialog(this, "Please enter issue Date !");
        }
     //  else if(returndatetf.getText().equals(""))
    //    {
    //     JOptionPane.showMessageDialog(this, "Please enter return Date !");
    //    }
        else if(librarianOidtf.getText().equals(""))
        {
         JOptionPane.showMessageDialog(this, "Please enter Librarian Official ID !");
        }
        
        //===========date
        
  
        //...................
        
        if(!getDataPerson.getLibCardExistFromDB(libcardno))
        {
        JOptionPane.showMessageDialog(this, "Sorry .. Invalid Library Card!");
        
        }
        else if(!getDataBooksDBobj.getBookIdExistFromDB(booksId))
        {
        JOptionPane.showMessageDialog(this, "Sorry .. Invalid Books Id!");
        
        }
        else if(!getDataLib.getOfficerExistFromDB(libOfficialID))
        {
        JOptionPane.showMessageDialog(this, "Sorry .. Invalid Librarian Official ID!");
        }
        
        if(!(getIssuedBooksNumber<1))
        {
        JOptionPane.showMessageDialog(this, "Sorry .. This Library card already taken "+getIssuedBooksNumber+" books..");
        
        }
        
        if((!librarycardtf.getText().equals(""))&&(!booksidtf.getText().equals(""))&&(!issuedatetf.getText().equals(""))&&(!returndatetf.getText().equals(""))&&(!librarianOidtf.getText().equals(""))
                &&(getDataPerson.getLibCardExistFromDB(libcardno))&&(getDataBooksDBobj.getBookIdExistFromDB(booksId))&&(getDataLib.getOfficerExistFromDB(libOfficialID))&&(getIssuedBooksNumber<1))
        {
        
            InsertServiceDB insertService=new InsertServiceDB();
            
            insertService.InsertToDB(libOfficialID, libcardno, booksId, issueDate, returnDate);
            
            GetDataFromBooksDB getavailablebook=new GetDataFromBooksDB();
            int  Booksnum= getavailablebook.getAvailableBooksFromDB(booksId);
            
            UpdateIssueBooksDataPersonDB updateIss=new UpdateIssueBooksDataPersonDB(permittableIssueBookNumber,libcardno);
            
            if(Booksnum!=0){
            String booksNum= String.valueOf(Booksnum-1);
                UpdateBooksNumber updateBooks=new UpdateBooksNumber(booksNum, booksId);
            }
             JOptionPane.showMessageDialog(this, "Thanks.. service granted......");
              JOptionPane.showMessageDialog(this, "Enter Refresh to Update...");
              
              
              librarycardtf.setText("");
              booksidtf.setText("");
              issuedatetf.setText("");
              returndatetf.setText("");
              librarianOidtf.setText("");
              returndatetf.setText("");
              
            
              
            
        }
        else
        {
        JOptionPane.showMessageDialog(this, "Invalid... info... please try again...");
        }
        
    }//GEN-LAST:event_serveOkButtonActionPerformed

    
    public static String getDate(Calendar cal){
        return "" + cal.get(Calendar.DATE) +"/" +"0"+
                (cal.get(Calendar.MONTH)+1) + "/" + cal.get(Calendar.YEAR);
    }
    
    
    
    
    private void serveCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serveCancelButtonActionPerformed
            
              librarycardtf.setText("");
              booksidtf.setText("");
              issuedatetf.setText("");
              librarianOidtf.setText("");
              returndatetf.setText("");
              
              this.dispose();
    }//GEN-LAST:event_serveCancelButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
      ReturnFrame returnObj=new ReturnFrame();
      returnObj.setVisible(true);
      returnObj.setLocationRelativeTo(null);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void issuedatetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedatetfActionPerformed
        String issueDate= issuedatetf.getText().toString();
        if(issueDate!=null){
        SimpleDateFormat dateFormat = new SimpleDateFormat( "dd/MM/yyyy" );
        Calendar cal = Calendar.getInstance();
        try {
            cal.setTime( dateFormat.parse( issueDate) );
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Date should not be blanked...");
        }
        cal.add( Calendar.DATE, 15 );
        
       // System.out.println(">>> "+getDate(cal));
        
        returndatetf.setText(getDate(cal));
        }
    }//GEN-LAST:event_issuedatetfActionPerformed

    private void returndatetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returndatetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returndatetfActionPerformed

    private void deleteBooksDBbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBooksDBbuttonActionPerformed
        String getUniqueValue= JOptionPane.showInputDialog(this, "Please Enter Super String :", "Input Super String: ", JOptionPane.OK_CANCEL_OPTION);
        if(getUniqueValue!=null)
        {
        
       //     DeleteDataBookDB deleteBook=new 
        
        }
        else
        {
        JOptionPane.showMessageDialog(this, "You Must Have To Input Super keyword.", "Wrong Value", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_deleteBooksDBbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
     public void setList()
    {
    
                String getBooksName[]= getDataBooksDBobj.getBNFromDB();
                int lengthofid=getDataBooksDBobj.LastID();
                
              //  System.out.println(">>"+lengthofid);
                if(lengthofid!=0){
                    DefaultListModel dlm=new DefaultListModel();
                
                     for(String wan: getBooksName)
                        {
                           // System.out.println(wan);
                            if(wan!=null) {
                             //   System.out.println("..1"+wan);
                                    dlm.addElement(wan);
                               //     System.out.println(">>>>"+dlm.toString());
                                }
                        }
                
                    
                     
                         bookList.setModel(dlm);
                         //System.out.println(">>>>>>"+jList1);
                }
                else
                {
              //  JOptionPane.showMessageDialog(rootPane,"Sorry.. there is no item..!", "Error !", JOptionPane.ERROR_MESSAGE);
                DefaultListModel dlm=new DefaultListModel();
                dlm.addElement("No Books In DB");
                bookList.setModel(dlm);
                }
    
    }
    
      public void setPersonList()
    {
    
                String getPersonName[]= getDataPerson.getPNFromDB();
                int lengthofid=getDataPerson.LastID();
                
              //  System.out.println(">>"+lengthofid);
                if(lengthofid!=0){
                    DefaultListModel dlm=new DefaultListModel();
                
                     for(String wan: getPersonName)
                        {
                           // System.out.println(wan);
                            if(wan!=null) {
                             //   System.out.println("..1"+wan);
                                    dlm.addElement(wan);
                               //     System.out.println(">>>>"+dlm.toString());
                                }
                        }
                
                    
                     
                         personList.setModel(dlm);
                         //System.out.println(">>>>>>"+jList1);
                }
                else
                {
              //  JOptionPane.showMessageDialog(rootPane,"Sorry.. there is no item..!", "Error !", JOptionPane.ERROR_MESSAGE);
                DefaultListModel dlm=new DefaultListModel();
                dlm.addElement("No Member In DB");
                personList.setModel(dlm);
                }
    
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceFormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceFormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceFormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceFormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ServiceFormMain serviceFormMainobj=new ServiceFormMain();
         serviceFormMainobj.setVisible(true);
         serviceFormMainobj.setLocationRelativeTo(null);
         serviceFormMainobj.setList();
         serviceFormMainobj.setPersonList();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList bookList;
    private javax.swing.JList booksInfoList;
    private javax.swing.JTextField booksidtf;
    private javax.swing.JButton deleteBooksDBbutton;
    private javax.swing.JButton deleteFineDBButton;
    private javax.swing.JButton deletePersonDBbutton;
    private javax.swing.JButton deleteServiceDBbutton;
    private javax.swing.JButton fineButton;
    private javax.swing.JButton insertBooksButton;
    private javax.swing.JButton insertPersonbutton;
    private javax.swing.JTextField issuedatetf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField librarianOidtf;
    private javax.swing.JTextField librarycardtf;
    private javax.swing.JList personInfoList;
    private javax.swing.JList personList;
    private javax.swing.JButton refreshBooksInfobutton;
    private javax.swing.JButton refreshMembersInfobutton;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField returndatetf;
    private javax.swing.JButton serveCancelButton;
    private javax.swing.JButton serveOkButton;
    private javax.swing.JButton servicebutton;
    // End of variables declaration//GEN-END:variables
}
