/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPack;

import DatabasePack.GetPack.GetDataFromServiceDB;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author faysal
 */
public class ServiceForm extends javax.swing.JFrame {

    
    GetDataFromServiceDB getServiceinfo=new GetDataFromServiceDB();
    
  
    /** 
     * Creates new form ServiceForm
     */
    
    
    
    private static final Object[][] rowData = {};
private static final Object[] columnNames = {"Librarian Official ID: ", "Library Card No: ","Books ID: ","Issue Date: ", "Return Date: "};
    

DefaultTableModel listTableModel;




    public ServiceForm() {
        
        initComponents();
        
           String gk[][]=getServiceinfo.getAllServiceInfoFromDB();
               
      
        
                
                
                              
       for(int i=0;i<getServiceinfo.LastID();++i)
      {
          for(int j=0;j<1;++j)
          {
                   
          listTableModel.addRow(new Object[]{gk[i][j],gk[i][j+1],gk[i][j+2],gk[i][j+3],gk[i][j+4]});
               
          }  
          
      }        
                
   /*
        for (int i = 1; i < 5; i++) {
        String rowString = "Quiz #" + i;
        listTableModel.addRow(new Object[]{rowString, "ICON", "ICON"});
    }
        
      */  
        
        // setServiceList();
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        serviceRefreshButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Services :");
        setIconImage(new ImageIcon(getClass().getResource("/icon/icon1.jpg")).getImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Services");

        jTable1.setModel(listTableModel = new DefaultTableModel(rowData, columnNames));
        jScrollPane1.setViewportView(jTable1);

        serviceRefreshButton.setText("Refresh");
        serviceRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceRefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(serviceRefreshButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceRefreshButton))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serviceRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceRefreshButtonActionPerformed
         
       int getLid=getServiceinfo.LastID();
       
        if(getLid!=0) {
            
            if(getLid==listTableModel.getRowCount()){
          //  System.out.println(getServiceinfo.LastID());
            
            for(int lastId=getServiceinfo.LastID();lastId>0;lastId--){
           listTableModel.removeRow(lastId-1);
          //     System.out.println(lastId-1);
            
            }
            }
            else
            {
          //  System.out.println("More id...");
            listTableModel.addRow(new Object[]{"","","","",""});
            for(int lastId=getServiceinfo.LastID();lastId>0;lastId--){
           listTableModel.removeRow(lastId-1);
              // System.out.println(lastId-1);
            
            }
            }
        }
     
        
        
        
        //   System.out.println(getServiceinfo.LastID());
        
        String gk[][]=getServiceinfo.getAllServiceInfoFromDB();
               
                   
       for(int i=0;i<getServiceinfo.LastID();++i)
      {
          for(int j=0;j<1;++j)
          {
                   
          listTableModel.addRow(new Object[]{gk[i][j],gk[i][j+1],gk[i][j+2],gk[i][j+3],gk[i][j+4]});
               
          }  
          
      }        
    }//GEN-LAST:event_serviceRefreshButtonActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceForm().setVisible(true);
            }
        });
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton serviceRefreshButton;
    // End of variables declaration//GEN-END:variables
}
